---

- name: Make plugin directory
  file: 
    path: "{{es_home}}/plugins/ik"
    state: directory
    mode: "0755"

- name: Copy plugin file
  unarchive: src="{{ ik.file }}" dest="{{es_home}}/plugins/ik"
  notify: restart elasticsearch

#Set permissions on plugins directory
- name: Set Plugin Directory Permissions
  file: state=directory path={{ es_home }}/plugins owner={{ es_user }} group={{ es_group }} recurse=yes
