# ---
# # file: tasks/set-role-variables.yml
# # set necessary role variables.
# #

# - name: compose url for downloading file, if necessary
#   set_fact:
#     es_tarball: elasticsearch-{{ es_version }}
# - name: compose url for downloading file, if necessary
#   set_fact:
#     es_tarball_url:  "{{ es_download_base_url }}/{{ es_tarball }}.tar.gz"

- debug: var=es_version
- name: compose url for downloading file, if necessary
  set_fact:
    es_tarball: elasticsearch-{{ es_version }}
- name: compose url for downloading file, if necessary
  set_fact:
    es_tarball_url:  "{{ es_download_base_url }}/{{ es_tarball }}.tar.gz"
